Repository RAR1741/RA20_RobotCode, pull requests merged in 2020-02, with the labels that each got.

#16 Drive module
  src/main/java/frc/robot/DriveModule.java
  src/main/java/frc/robot/Drivetrain.java
  src/main/java/frc/robot/Robot.java
Labels: ready to test

#9 Add navX gyro
  src/main/java/frc/robot/Robot.java
  vendordeps/navx_frc.json
Labels: enhancement

#17 Add Powercell Detection
  src/main/java/frc/robot/Drivetrain.java
  src/main/java/frc/robot/PowercellDetection.java
  src/main/java/frc/robot/Robot.java
  src/main/java/frc/robot/Target.java
Labels: enhancement, ready to test, requires robot
