Repository RAR1741/RA20_RobotCode, pull requests merged in 2020-01, with the labels that each got.

#6 Add Limelight vertical length getter method
  src/main/java/frc/robot/Limelight.java
  src/main/java/frc/robot/Robot.java
Labels: enhancement, ready to test

#12 Add SnobotSim
  .gitignore
  build.gradle
  simulator_config/joystick_config.properties
  simulator_config/simulator_config.properties
  simulator_config/simulator_config.yml
  snobotsim/SnobotSim.json
  snobotsim/snobot_sim.gradle
Labels: enhancement

#11 Update build.gradle
  build.gradle
Labels: ready to test

#5 Add Drivetrain
  .vscode/settings.json
  src/main/java/frc/robot/Drivetrain.java
  src/main/java/frc/robot/Robot.java
Labels: enhancement, ready to test
